In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
"""
Create a CSV file called “Movies.csv” with details of 10 movies - Movie Name, Language, Genre, Rating, Review. 
a. Read CSV file into a dataframe and find the movie with the highest rating. 
b. Write the details of all Hindi movies into a file “HindiMovies.csv”. 
"""

mdf = pd.read_csv("Movies.csv")

print("Top Rated Movies")
display(mdf[mdf["Rating"] == mdf["Rating"].max()])

print("Hindi Movies")
hindi_df = mdf[mdf["Language"] == "Hindi"]
display(hindi_df)
hindi_df.to_csv("Hindi Movies.csv", index=False)
print("Written Hindi movies to csv file.")

Top Rated Movies

,Movie Name,Language,Genre,Rating,Review
0,12th Fail,Hindi,Biographical Drama,8.7,"Inspiring real-life story of perseverance, wid..."
3,777 Charlie,Kannada,Adventure/Drama,8.7,"Heartwarming story of a man and his dog, celeb..."

Hindi Movies

,Movie Name,Language,Genre,Rating,Review
0,12th Fail,Hindi,Biographical Drama,8.7,"Inspiring real-life story of perseverance, wid..."

Written Hindi movies to csv file.

In [3]:
"""
For the CEREALS dataset, perform data preprocessing and answer the following questions.
a. Create a table with the 5 number summary of all the numeric attributes. 
b. For each of the numeric attributes (proteins upto vitamins), identify and replace all missing data(indicated with -1) with 
the arithmetic mean of the attribute. 
c. Create a table with the 5 number summary of all the numeric attributes after treating missing values.
d. For each numeric attribute (proteins upto vitamins), identify and replace all noisy data with the median of attribute.  
e. Create a table with the 5 number summary of all the numeric attributes after treating noisy values.
"""

cdf = pd.read_csv("cereals.csv")
numeric_cols = cdf.loc[:, "protein":"vitamins"].columns
# summary = 

# a. Create a table with the 5 number summary of all the numeric attributes.
print("Before processing")
display(cdf[numeric_cols].describe().loc['min':'max', :])

# b. For each of the numeric attributes (proteins upto vitamins), identify and replace all missing data(indicated with -1) with 
# the arithmetic mean of the attribute.
cdf.replace(-1, np.NaN, inplace=True)
for col in numeric_cols:
    cdf.fillna({col: cdf[col].mean()}, inplace=True)

# c. Create a table with the 5 number summary of all the numeric attributes after treating missing values.
print("After replacing missing values with mean")
display(cdf[numeric_cols].describe().loc['min':'max', :])

# d. For each numeric attribute (proteins upto vitamins), identify and replace all noisy data with the median of attribute.
for col in numeric_cols:
    q1 = cdf[col].quantile(0.25)
    q3 = cdf[col].quantile(0.75)
    iqr = q3 - q1
    low = q1 - 1.5*iqr
    high = q3 + 1.5*iqr
    
    cdf[col] = cdf[col].astype(float)
    median_val = cdf[col].median()
    cdf.loc[(cdf[col] < low) | (cdf[col] > high), col] = median_val

# e. Create a table with the 5 number summary of all the numeric attributes after treating noisy values.
print("After treating noisy values")
display(cdf[numeric_cols].describe().loc['min':'max', :])

Before processing

     protein   fat  sodium  fiber  carbohydrates  sugars  vitamins
min      1.0  0.00    -1.0   1.00          -1.00   -1.00      -1.0
25%      2.0  0.25   185.0   1.00          21.00    6.25      25.0
50%      2.5  1.00   205.0   2.00          22.00    9.50      25.0
75%      3.0  1.75   217.5   2.75          23.75   12.00      25.0
max      6.0  2.00   250.0   4.00          26.00   15.00      25.0

AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.